name: Update Frontend Prod

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/frontend.yml

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_DEFAULT_REGION: eu-central-1
  credentials-account: arn:aws:iam::275567994947:role/synonyms-prod-gh-actions-S3-role
  ENV_NAME: prod
  CF_DISTRIBUTION: E22GFRHGJHAV2X
  REACT_APP_API_URL: http://synonyms-prod-alb-232525125.eu-central-1.elb.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Get's access to aws
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.credentials-account }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build
        working-directory: ./frontend
        run: npm run build

      # Uploads the files to S3
      - name: Deploy to S3
        run: aws s3 sync ./frontend/build/ s3://synonyms-${{env.ENV_NAME}}-frontend-275567994947 --delete

      # Invalidates cloudfront cache
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{env.CF_DISTRIBUTION}} --paths "/*"
