name: PR to main

on:
  pull_request:
    branches: [main]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install deps
        working-directory: ./backend
        run: |
          echo "Installing deps for test"
          npm ci

      - name: Transpile typescript
        working-directory: ./backend
        run: |
          echo "Running tsc"
          npm run build

      # Runs the Chai tests with Mocha
      - name: Test
        working-directory: ./backend
        run: |
          echo "Running tests"
          npm run test
          echo "tests succeded"

  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build
        working-directory: ./frontend
        run: npm run build

      #TODO add frontend testing

  test_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4

      # Inits Terraform localy without needing access to the state in S3
      - name: Terraform Init
        working-directory: ./infra
        run: terraform init -backend=false

      #Validates the syntax of our .tf files
      - name: Terraform Validate
        working-directory: ./infra
        run: terraform validate
